name: 22.04 libsystemd-dev Error

on:
  push:

jobs:
  work:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          sudo apt update
          sudo apt install systemd=249.11-0ubuntu3 libsystemd-dev=249.11-0ubuntu3
