name: Test

on: workflow_dispatch

jobs:
  inline:
    runs-on: ubuntu-latest
    steps:
      - run: |
          function teardown {
            status=$?
            echo "Teardown status ${status}"
            exit "${status}"
          }

          trap teardown SIGINT

          ps
          echo Sleeping...
          sleep 60 & wait $!
          
  external-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "The script pid is $"
          bash .github/workflows/test.sh
          
