name: Test

on: workflow_dispatch

jobs:
  job-one:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          touch file.txt
          git status
