on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          VAR=9d2034d666b1
          echo "OUTPUT: $GITHUB_OUTPUT"
          //echo "version=${VAR}" >> $GITHUB_OUTPUT
          //echo "version=${VAR}" >> "$GITHUB_OUTPUT"
