name: Test

on: workflow_dispatch


jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ fromJSON(steps.step1.outputs.test) }}
    steps:
      - uses: actions/checkout@v3
      - id: step1
        run: |
          CONT=$(cat data.json)
          echo "test=(echo $CONT)" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: |
          echo "$OUTPUT1"
          echo "${{ needs.job1.outputs.output1.repository.packages.nodes.versions.nodes.id }}"
