name: Test

on: workflow_dispatch


jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[\"one\":{\"project\":\"foo\",\"config\":\"Debug\"},\"two\":{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ fromJSON(needs.job1.outputs.matrix).include.one }}"
