on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-one:
    runs-on: ubuntu-latest
    outputs:
      content: ${{ steps.my_string.outputs.thisString }}
    steps:
      - name: create string
        run: |
          MY_STRING=$(cat << EOF
          first line
          second line
          third line
          EOF
          )
          MY_STRING="${MY_STRING//'%'/'%25'}"
          MY_STRING="${MY_STRING//$'\n'/'%0A'}"
          MY_STRING="${MY_STRING//$'\r'/'%0D'}"
          echo $MY_STRING
          echo "thisString=$MY_STRING" >> $GITHUB_OUTPUT
        id: my_string
      - name: display string
        run: |
          echo "The string is: ${{ steps.my_string.outputs.content }}"
