on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - id: out
        run: |
          VAR=$(echo 'value')
          echo "vars=${VAR}" >> $GITHUB_OUTPUT
