name: Test-Env
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-20.04
    environment:
      name: Test-Env
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: "translation-and-audio"
          path: |
            folder
