on:
  push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
    
      - id: cache-this
        uses: actions/cache@v3
        with:
          path: mydir
          key: my-key-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            my-key
        
      - if: steps.cache-this.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.cache-this.outputs.cache-hit }}
          mkdir mydir
          echo "Here is my file" > ./mydir/file.txt
