on:
  push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-22.04
    steps:
    
      - id: cache-this
        uses: actions/cache@v3
        with:
          path: mydir
          key: ${{ matrix.os }}-mykeynew-eccetera
          restore-keys: |
            ${{ matrix.os }}-mykeynew
        
      - if: steps.cache-this.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.cache-this.outputs.cache-hit }}
          mkdir mydir
          echo "Here is my file" > ./mydir/file.txt
