name: Fail then Pass on Re-run

on: [push]

jobs:
  verify-attempt:
    runs-on: ubuntu-latest
    env:
      FLAG: false
    steps:
      - id: check
        run: |
          ID=$(curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs |
          jq .workflow_runs[0].id)

          RESP=$(curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/$ID/attempts/2 |
          jq .message)

          if [ $RESP != "Not Found" ]
          then
            echo "FLAG=$true" >> $GITHUB_ENV
          fi
          
      - if: ${{ env.FLAG }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('FAIL')
