on:
  push:

jobs:
  work:
    runs-on: windows-2019
    env:
      VULKAN_SDK_VER: 1.2.176.1
    steps:
      - run: |
          curl -o VulkanSDK-Installer.exe https://sdk.lunarg.com/sdk/download/${{ env.VULKAN_SDK_VER }}/windows/VulkanSDK-${{ env.VULKAN_SDK_VER }}-Installer.exe?Human=true
          .\VulkanSDK-Installer.exe /S

      - run: C:\VulkanSDK\${{ env.VULKAN_SDK_VER }}\Bin\vkvia.exe
      
      - name: Setup tmate session if failure
        if: false #${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 20
