on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo VAR=("nothing"
      - uses: actions/setup-node@v3
        with:
          node-version: ">=16"
      
