on:
  push:
    
env:
  DATE: date +'%Y-%m-%d'

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo $DATE
      - if: ${{ $DATE == '2022-10-27' }}
        run: echo 'Worked!'
      
