on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          case :$SHELLOPTS: in
            *:posix:*) echo "POSIX mode enabled" ;;
            *)         echo "POSIX mode not enabled" ;;
          esac
      - run: echo <(echo ***)
      
