on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo <(echo ${{ secrets.NON_PAREN_SECRET }})
      - run: echo <(echo ${{ secrets.PAREN_SECRET }})
      
