on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          if [ -f /usr/lib/systemd/user/gpg-agent.service ]; then
            mkdir ~/.gnupg
            cat <<EOT >> ~/.gnupg/gpg-agent.conf
            allow-preset-passphrase
            default-cache-ttl 60
            max-cache-ttl 50
          EOT
            chmod 600 ~/.gnupg/*
            chmod 700 ~/.gnupg
            systemctl --user restart gpg-agent
          else
            gpg-agent --daemon --allow-preset-passphrase \
            --default-cache-ttl 60 --max-cache-ttl 60
          fi
          
          gpg --pinentry-mode loopback \
          --passphrase-file <(echo passphrase) \
          --import
      
