on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-name:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: ssh-add -h
