on:
  push:
  #pull_request:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      SETUP: ${{ steps.commit_message.outputs.value }}
    steps:
      - id: commit_message
        run: |
          if ( ${{ github.event_name }} == 'workflow_dispatch' )
            result=$(
              curl \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }} |
              jq .commit.message
            )
          else
            result=${{ github.event.head_commit.message }}
          fi
          
          if ( (expr length $result) > 25 )
            result = "${result:0:25}"
          fi
          
          echo "value=$result" >> $GITHUB_OUTPUT
          
  job-one:
    runs-on: ubuntu-latest
    run-name: '[${{ github.ref_name }} ] ${{ jobs.setup.outputs.SETUP }}'
    steps:
      - run: echo 'This is a job!'
