on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://alpine:latest
        with:
          args: sh -c '/a/b/c command > output.log'
