on:
  push:

jobs:
  job-fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - if: false
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('failure');
