on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - if: false
        id: id-name
        name: ID NAME
        uses: docker://alpine:latest
        env:
          INPUT_ARGS: sh -c '/a/b/c command > output.log'
