on:
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  job-fail:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - if: false
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('failure');
