on:
  workflow_dispatch:
  pull_request:

jobs:
  job-fail:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo start
          sleep 180
          echo done
      - if: false
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('failure');
