on:
  push:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \ 
          -H "Authorization: token ${{ GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d '{"tag_name":"v64",
              "target_commitish":"main",
              "name":"v64",
              "body":"Description of the release",
              "draft":false,
              "prerelease":false,
              "generate_release_notes":false}'

  pull-latest:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
          -H "Accept: application/vnd.github+json" \ 
          -H "Authorization: token ${{ GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/releases/latest
    
    
    
    
#      - if: false
#        uses: actions/github-script@v6
#        with:
#          script: |
#            core.setFailed('failure');
