on:
  push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - id: cache-primes
        uses: actions/cache@v3
        with:
          path: prime-numbers
          key: primes

      - if: steps.cache-primes.outputs.cache-hit != 'true'
        run: |
          mkdir prime-numbers
          echo "FILE CONTENT" > prime-numbers/file.txt
