on:
  push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - uses: ./.github/actions
      
  job2:
    uses: anthms/public-actions-depot/.github/workflows/reusable-callable.yml@main
