on:
  push:
  #pull_request:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions

  job-two:
    uses: anthms/event-test/.github/workflows/blank.yml@main
    
