name: CI

on:
  push:
      
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          for value in {1..50}
          do
            echo "Print this --> $value"
          done
          
          echo All done
