name: CI

on:
  push:
      
jobs:
  job1:
    if: false
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - run: |
          for value in {1..50}
          do
            echo "Print this --> $value"
            sleep 1
          done
          
          echo All done
      - uses: actions/checkout@v3
