name: Set Output Repro

on:
  workflow_dispatch:

jobs:
  job-one:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Old method
        id: old_method
        run: echo "::set-output name=option::THIS_ACTUALLY_WORKS"

      - name: New method
        id: new_method
        run: echo "option=THIS_NO_LONGER_WORKS" >> $GITHUB_OUTPUT

      - name: With bash
        shell: bash
        run: |
          echo "Old method: ${{ steps.old_method.outputs.option }}"
          echo "New method: ${{ steps.new_method.outputs.option }}"
          
      - name: With pwsh
        shell: pwsh
        run: |
          echo "Old method: ${{ steps.old_method.outputs.option }}"
          echo "New method: ${{ steps.new_method.outputs.option }}"
          
      - name: With PowerShell
        shell: powershell
        run: |
          echo "Old method: ${{ steps.old_method.outputs.option }}"
          echo "New method: ${{ steps.new_method.outputs.option }}"
          
      - name: With cmd
        shell: cmd
        run: |
          echo "Old method: ${{ steps.old_method.outputs.option }}"
          echo "New method: ${{ steps.new_method.outputs.option }}"
          
