name: Validate macOS build

on:
  workflow_dispatch:

jobs:
  validate-12:
    runs-on: macos-12
    steps:
      - name: Download archive
        run: curl -L 'https://noop-desktop.s3.us-west-2.amazonaws.com/desktop/Noop-2.0.19-pr774.1-mac.zip' > /tmp/Noop.zip
      - name: Decompress archive
        run: bsdtar -xzf /tmp/Noop.zip -C /tmp
      - name: List files
        run: ls -al /tmp/
      - name: validate
        run: spctl --verbose=4 --assess --type execute /tmp/Noop.app
        
  validate-11:
    runs-on: macos-11
    steps:
      - name: Download archive
        run: curl -L 'https://noop-desktop.s3.us-west-2.amazonaws.com/desktop/Noop-2.0.19-pr774.1-mac.zip' > /tmp/Noop.zip
      - name: Decompress archive
        run: bsdtar -xzf /tmp/Noop.zip -C /tmp
      - name: List files
        run: ls -al /tmp/
      - name: validate
        run: spctl --verbose=4 --assess --type execute /tmp/Noop.app
        
  validate-10:
    runs-on: macos-10.15
    steps:
      - name: Download archive
        run: curl -L 'https://noop-desktop.s3.us-west-2.amazonaws.com/desktop/Noop-2.0.19-pr774.1-mac.zip' > /tmp/Noop.zip
      - name: Decompress archive
        run: bsdtar -xzf /tmp/Noop.zip -C /tmp
      - name: List files
        run: ls -al /tmp/
      - name: validate
        run: spctl --verbose=4 --assess --type execute /tmp/Noop.app
        
